[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
environment=TZ="Europe/Moscow"

[program:web_server]
command=python main.py
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/supervisor/web_server.err.log
stdout_logfile=/var/log/supervisor/web_server.out.log
environment=TZ="Europe/Moscow"

[program:daily_updater]
command=python daily_updater.py
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/supervisor/daily_updater.err.log
stdout_logfile=/var/log/supervisor/daily_updater.out.log
environment=TZ="Europe/Moscow"